# -*- coding: utf-8 -*-
"""Expirement 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1neaCd-sDhm4rNrkGyso-04JKNet_BSAP
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

# Load Dataset
df = pd.read_csv("placement_predict_50k Dataset.csv")

# 1. First five rows
print("FIRST FIVE ROWS")
print(df.head())

# 2. Dataset Shape
print("\nDATASET SHAPE")
print(df.shape)

# 3. Column Names
print("\nCOLUMN NAMES")
print(df.columns)

# 4. Data Types
print("\nDATA TYPES")
print(df.dtypes)

# 5. Dataset Information
print("\nDATASET INFORMATION")
df.info()

# 6. Statistical Summary
print("\nSTATISTICAL SUMMARY")
print(df.describe())

# 7. Missing Values
print("\nMISSING VALUES")
print(df.isnull().sum())

# 8. Duplicate Rows
print("\nDUPLICATE ROWS")
print(df.duplicated().sum())

# 9. Placement Status Distribution
print("\nPLACEMENT STATUS DISTRIBUTION")
print(df["PlacementStatus"].value_counts())

# 10. Placement Status Percentage
print("\nPLACEMENT STATUS PERCENTAGE")
print(df["PlacementStatus"].value_counts(normalize=True) * 100)

import matplotlib.pyplot as plt

# Placement Status Count
df["PlacementStatus"].value_counts().plot(kind="bar")

plt.title("Placement Status Distribution")
plt.xlabel("Placement Status")
plt.ylabel("Count")

plt.show()