# -*- coding: utf-8 -*-
"""Machine Learning

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cDwYPB-yNAKozYcXW_MvP2zRIA-tXEg4
"""

x = 5
y = 3.14
name = "CGPA"
is_placed = True

print(x, type(x))
print(y, type(y))
print(name, type(name))
print(is_placed, type(is_placed))

# --- ARTHEMATIC OPERATIONS ---
a = 7
b = 2
print("a+b=",a+b)
print("a-b=",a-b)
print("a*b=",a*b)
print("a/b=",a/b)
print("a%b=",a%b)
print("a//b=",a//b)
print("a**2=",a**2)

cgpa = 8.4
print("cgpa == 8.4 :", cgpa == 8.4)
print("cgpa > 8 :", cgpa > 8)
print("cgpa < 6 :", cgpa < 6)

model_name = "Logistic Regression"
accuracy = 0.87345
print("Accuracy of " + model_name + " is "+str(accuracy))
print(f"Accuracy of {model_name} is {accuracy}")
print(f"Accuracy of {model_name} is {accuracy:.3f}")

